version: "3.9"

services:
  db:
    container_name: db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: backend/
    command: bash -c "./start.sh"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
      - PG_HOST=db

  frontend:
    container_name: nginx
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend