"""initq

Revision ID: 6bdf4bd7f9eb
Revises: e3c86463f433
Create Date: 2022-11-09 00:17:59.655843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdf4bd7f9eb'
down_revision = 'e3c86463f433'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
