"""created relationship

Revision ID: 75335e95ea22
Revises: e363b8170903
Create Date: 2022-11-21 11:09:12.806808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75335e95ea22'
down_revision = 'e363b8170903'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'user_id')
    # ### end Alembic commands ###
