"""

Revision ID: 826fa654674d
Revises: 4fac6dffb4f0
Create Date: 2022-11-05 17:19:45.138448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826fa654674d'
down_revision = '4fac6dffb4f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disable')
    # ### end Alembic commands ###
