"""initq

Revision ID: cf90c32ef77c
Revises: ec19e253a464
Create Date: 2022-11-08 23:24:21.887296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf90c32ef77c'
down_revision = 'ec19e253a464'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'refresh_token',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('users', 'expires_token',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'expires_token',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'refresh_token',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###
